### ISSUE TITLE
Should use `proof` and `jws` terms

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/lds-ed25519-2018#1]
We're moving LD Signatures to be based on top of LD Proofs so any potential implementers should be aware that this spec should be updated to use `proof` (rather than `signature`). Also, as we're moving to support JWS detached signatures for JOSE compatibility, the term `signatureValue` should also be replaced with `jws`.

A first cut at implementing this signature suite is here:

https://github.com/digitalbazaar/jsonld-signatures/blob/master/lib/suites/Ed25519Signature2018.js

We need to clean up both this spec and the one it extends (The Linked Data Signature spec) to be more clear about what's going on with the details. The specs are "unimplementable" right now without tribal knowledge, IMO.

**Comment by peacekeeper** [comment]
Just FYI I'm aware of this and am tempted to update this spec right now accordingly, but I think I'd rather wait until the "upstream" LD Proofs and LD Signatures specs are updated.
