### ISSUE TITLE
Remove Key in the name

### ISSUE THREAD

**Issue by mikelodder7** [w3c-ccg/lds-ed25519-2018#2]
In some places you have Ed25519VerificationKey. Can we change it to be Ed25519SignatureVerification?

The context is already in a publicKey section so I feel "Key" is redundant.

**Comment by msporny** [comment]
> The context is already in a publicKey section so I feel "Key" is redundant.

I think this is a graph model confusion. "Ed25519SignatureVerificationKey"s are not always contained in "publicKey" properties. In some cases, you just get a raw array of objects back (for example, when you'd do something like a MongoDB database query), and in that case, "publicKey" doesn't exist to give you context. So, in that case, it's not redundant.

**Comment by peacekeeper** [comment]
`Ed25519SigningKey` was changed to `Ed25519SignatureVerificationKey2018`, fixed by 5505eba04df651bf061d51d816609d8fc2dff2bc
