### ISSUE TITLE
Mark as deprecated or move to ccg

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/lds-ed25519-2018#5]
I question whether we want to encourage separate linked data specs for signature suites which are referenced here: https://github.com/w3c-ccg/security-vocab

But not documented there...

A middle ground approach might be to define the term in:

https://github.com/w3c-ccg/security-vocab

But link from it to the full spec for the linked data crypto suite.... hosted in the ccg or elsewhere.

Personally I would rather see this repo deleted, and its content absorbed into w3c-ccg/security-vocab, see:

https://github.com/w3c-ccg/security-vocab/pull/14

**Comment by OR13** [comment]
cc @peacekeeper @msporny

**Comment by OR13** [comment]
Also if you wish for me to assist with closing down the DVCG you may want to make me a github owner. Regardless I will keep opening issues like this until the stuff we rely on is moved to the CCG, I just can't move it myself.

**Comment by msporny** [comment]
> Also if you wish for me to assist with closing down the DVCG you may want to make me a github owner.

I'm fine w/ doing that, but it's not my call. /cc CCG Chairs - @ChristopherA @kimdhamilton @jandrieu

**Comment by msporny** [comment]
Moved to W3C CCG, closing.

**Comment by msporny** [comment]
> Personally I would rather see this repo deleted, and its content absorbed into w3c-ccg/security-vocab, see

Doing so would centralize all LD cryptosuites, which is not ideal. We do have the LD Cryptosuite Registry, which is supposed to help people navigate the specs... not that I think it's easy at all right now. We may want to show where each spec is in the stack of specs in the introductory portion of every LD Security spec... providing a map with which to navigate might further address your concern @OR13 about ensuring everyone has the same sort of entry into this world.
